// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCes_5JUW_SDfo9pa3PLoJjKEgq1D8VW8Q',
    appId: '1:537072122339:web:a2ea46e7d380f0524a88d6',
    messagingSenderId: '537072122339',
    projectId: 'asegensa-43246',
    authDomain: 'asegensa-43246.firebaseapp.com',
    storageBucket: 'asegensa-43246.firebasestorage.app',
    measurementId: 'G-FDK31G7550',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lWCCTRasxjK3dY6dwtOYw5wJ3ILvk_Q',
    appId: '1:537072122339:android:fffcc1b4d9052d5a4a88d6',
    messagingSenderId: '537072122339',
    projectId: 'asegensa-43246',
    storageBucket: 'asegensa-43246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmvfbQfpj1b69eknZWt5M1KL7n8_Zbc_s',
    appId: '1:537072122339:ios:a657f9ea453420fb4a88d6',
    messagingSenderId: '537072122339',
    projectId: 'asegensa-43246',
    storageBucket: 'asegensa-43246.firebasestorage.app',
    iosBundleId: 'com.example.asegensa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmvfbQfpj1b69eknZWt5M1KL7n8_Zbc_s',
    appId: '1:537072122339:ios:a657f9ea453420fb4a88d6',
    messagingSenderId: '537072122339',
    projectId: 'asegensa-43246',
    storageBucket: 'asegensa-43246.firebasestorage.app',
    iosBundleId: 'com.example.asegensa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCes_5JUW_SDfo9pa3PLoJjKEgq1D8VW8Q',
    appId: '1:537072122339:web:03ccaac186e68c6b4a88d6',
    messagingSenderId: '537072122339',
    projectId: 'asegensa-43246',
    authDomain: 'asegensa-43246.firebaseapp.com',
    storageBucket: 'asegensa-43246.firebasestorage.app',
    measurementId: 'G-5BDEBJKXMG',
  );
}
